/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as ScanTicketsRouteImport } from './routes/scan-tickets'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PointsTableRouteImport } from './routes/points-table'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as NewsRouteImport } from './routes/news'
import { Route as NewPostRouteImport } from './routes/new-post'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MembersRouteImport } from './routes/members'
import { Route as JerseyRouteImport } from './routes/jersey'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyTicketCodeRouteImport } from './routes/verify-ticket.$code'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'

const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanTicketsRoute = ScanTicketsRouteImport.update({
  id: '/scan-tickets',
  path: '/scan-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsTableRoute = PointsTableRouteImport.update({
  id: '/points-table',
  path: '/points-table',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPostRoute = NewPostRouteImport.update({
  id: '/new-post',
  path: '/new-post',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const JerseyRoute = JerseyRouteImport.update({
  id: '/jersey',
  path: '/jersey',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTicketCodeRoute = VerifyTicketCodeRouteImport.update({
  id: '/verify-ticket/$code',
  path: '/verify-ticket/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => MessagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/feed': typeof FeedRoute
  '/fixtures': typeof FixturesRoute
  '/friends': typeof FriendsRoute
  '/gallery': typeof GalleryRoute
  '/jersey': typeof JerseyRoute
  '/members': typeof MembersRoute
  '/messages': typeof MessagesRouteWithChildren
  '/new-post': typeof NewPostRoute
  '/news': typeof NewsRoute
  '/players': typeof PlayersRoute
  '/points-table': typeof PointsTableRoute
  '/profile': typeof ProfileRoute
  '/registration': typeof RegistrationRoute
  '/results': typeof ResultsRoute
  '/scan-tickets': typeof ScanTicketsRoute
  '/sponsors': typeof SponsorsRoute
  '/teams': typeof TeamsRoute
  '/tickets': typeof TicketsRoute
  '/track-order': typeof TrackOrderRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/verify-ticket/$code': typeof VerifyTicketCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/feed': typeof FeedRoute
  '/fixtures': typeof FixturesRoute
  '/friends': typeof FriendsRoute
  '/gallery': typeof GalleryRoute
  '/jersey': typeof JerseyRoute
  '/members': typeof MembersRoute
  '/messages': typeof MessagesRouteWithChildren
  '/new-post': typeof NewPostRoute
  '/news': typeof NewsRoute
  '/players': typeof PlayersRoute
  '/points-table': typeof PointsTableRoute
  '/profile': typeof ProfileRoute
  '/registration': typeof RegistrationRoute
  '/results': typeof ResultsRoute
  '/scan-tickets': typeof ScanTicketsRoute
  '/sponsors': typeof SponsorsRoute
  '/teams': typeof TeamsRoute
  '/tickets': typeof TicketsRoute
  '/track-order': typeof TrackOrderRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/verify-ticket/$code': typeof VerifyTicketCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/feed': typeof FeedRoute
  '/fixtures': typeof FixturesRoute
  '/friends': typeof FriendsRoute
  '/gallery': typeof GalleryRoute
  '/jersey': typeof JerseyRoute
  '/members': typeof MembersRoute
  '/messages': typeof MessagesRouteWithChildren
  '/new-post': typeof NewPostRoute
  '/news': typeof NewsRoute
  '/players': typeof PlayersRoute
  '/points-table': typeof PointsTableRoute
  '/profile': typeof ProfileRoute
  '/registration': typeof RegistrationRoute
  '/results': typeof ResultsRoute
  '/scan-tickets': typeof ScanTicketsRoute
  '/sponsors': typeof SponsorsRoute
  '/teams': typeof TeamsRoute
  '/tickets': typeof TicketsRoute
  '/track-order': typeof TrackOrderRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/verify-ticket/$code': typeof VerifyTicketCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/feed'
    | '/fixtures'
    | '/friends'
    | '/gallery'
    | '/jersey'
    | '/members'
    | '/messages'
    | '/new-post'
    | '/news'
    | '/players'
    | '/points-table'
    | '/profile'
    | '/registration'
    | '/results'
    | '/scan-tickets'
    | '/sponsors'
    | '/teams'
    | '/tickets'
    | '/track-order'
    | '/messages/$conversationId'
    | '/u/$userId'
    | '/verify-ticket/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/feed'
    | '/fixtures'
    | '/friends'
    | '/gallery'
    | '/jersey'
    | '/members'
    | '/messages'
    | '/new-post'
    | '/news'
    | '/players'
    | '/points-table'
    | '/profile'
    | '/registration'
    | '/results'
    | '/scan-tickets'
    | '/sponsors'
    | '/teams'
    | '/tickets'
    | '/track-order'
    | '/messages/$conversationId'
    | '/u/$userId'
    | '/verify-ticket/$code'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/feed'
    | '/fixtures'
    | '/friends'
    | '/gallery'
    | '/jersey'
    | '/members'
    | '/messages'
    | '/new-post'
    | '/news'
    | '/players'
    | '/points-table'
    | '/profile'
    | '/registration'
    | '/results'
    | '/scan-tickets'
    | '/sponsors'
    | '/teams'
    | '/tickets'
    | '/track-order'
    | '/messages/$conversationId'
    | '/u/$userId'
    | '/verify-ticket/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FeedRoute: typeof FeedRoute
  FixturesRoute: typeof FixturesRoute
  FriendsRoute: typeof FriendsRoute
  GalleryRoute: typeof GalleryRoute
  JerseyRoute: typeof JerseyRoute
  MembersRoute: typeof MembersRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NewPostRoute: typeof NewPostRoute
  NewsRoute: typeof NewsRoute
  PlayersRoute: typeof PlayersRoute
  PointsTableRoute: typeof PointsTableRoute
  ProfileRoute: typeof ProfileRoute
  RegistrationRoute: typeof RegistrationRoute
  ResultsRoute: typeof ResultsRoute
  ScanTicketsRoute: typeof ScanTicketsRoute
  SponsorsRoute: typeof SponsorsRoute
  TeamsRoute: typeof TeamsRoute
  TicketsRoute: typeof TicketsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  UUserIdRoute: typeof UUserIdRoute
  VerifyTicketCodeRoute: typeof VerifyTicketCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-tickets': {
      id: '/scan-tickets'
      path: '/scan-tickets'
      fullPath: '/scan-tickets'
      preLoaderRoute: typeof ScanTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points-table': {
      id: '/points-table'
      path: '/points-table'
      fullPath: '/points-table'
      preLoaderRoute: typeof PointsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-post': {
      id: '/new-post'
      path: '/new-post'
      fullPath: '/new-post'
      preLoaderRoute: typeof NewPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jersey': {
      id: '/jersey'
      path: '/jersey'
      fullPath: '/jersey'
      preLoaderRoute: typeof JerseyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-ticket/$code': {
      id: '/verify-ticket/$code'
      path: '/verify-ticket/$code'
      fullPath: '/verify-ticket/$code'
      preLoaderRoute: typeof VerifyTicketCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof MessagesRoute
    }
  }
}

interface MessagesRouteChildren {
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConversationIdRoute: MessagesConversationIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FeedRoute: FeedRoute,
  FixturesRoute: FixturesRoute,
  FriendsRoute: FriendsRoute,
  GalleryRoute: GalleryRoute,
  JerseyRoute: JerseyRoute,
  MembersRoute: MembersRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NewPostRoute: NewPostRoute,
  NewsRoute: NewsRoute,
  PlayersRoute: PlayersRoute,
  PointsTableRoute: PointsTableRoute,
  ProfileRoute: ProfileRoute,
  RegistrationRoute: RegistrationRoute,
  ResultsRoute: ResultsRoute,
  ScanTicketsRoute: ScanTicketsRoute,
  SponsorsRoute: SponsorsRoute,
  TeamsRoute: TeamsRoute,
  TicketsRoute: TicketsRoute,
  TrackOrderRoute: TrackOrderRoute,
  UUserIdRoute: UUserIdRoute,
  VerifyTicketCodeRoute: VerifyTicketCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
